//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TekBqzXmDI8/nLYGHOl0t+0GY0B0SU2tBRXkAXzKoFFS1U9qo9Sdvk9EVbfs8Bqs1tlSTDlFe/AJbVYGpI7ln3oS8o/AwZfhYkJ6TlTGNgqG8K2BFmFxJU/BdlRbVdsUiKg9Z+mALGL1JU00POUGEHFTMIV28RCJuBtO1V0JHNP3zF1gta63WoHq+DQgq6hVh/H2Whh6hvMSZEnTOtaRWGElpk6kVMBhkUfcqjvLE1z3agWL7qh3q5isbMbqwahGaJc28ef2CZbf562O0BXeWRDAtZnYIDl4RVec/hM66F1ZQlfSRAwzCU+idIeSdgJQXiv+o3UcUAiKBLvPnJjhJjKnn3YUb41ys9pb5NQFVAyfoBpJ8dTao1FcCxlPCuifvG5RSmFMF2JMHe7c6Jp1EusWanKtc4KKQkYvCZMT/Kx7DN06+Z8zniTunO4Vfskf8bQY2hFRO+kr/Hnec27Dp8bscvlNzm6NqsgtGga4tN/1CNsfD2BPzrBl14vOc50e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassPhrase {
            get {
                return ResourceManager.GetString("PassPhrase", resourceCulture);
            }
        }
    }
}
